#!/bin/sh

cd "$(dirname "$0")"

file="$1"

echo "Generating '$file'"

src="htdocs/$file.php"
dst="build/htdocs/$file"

mkdir -p "$(dirname "$dst")"

php -c preprocess/php.ini preprocess/process.php "config.php" "$src" "$dst"
